/**
 * Okta API
 * Allows customers to easily access the Okta API
 *
 * OpenAPI spec version: 1.11.0
 * Contact: devex-public@okta.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package gov.texas.okta.client.api;

import java.time.LocalDateTime;
import java.time.Year;

import org.junit.Before;
import org.junit.Test;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

import gov.texas.esb.cxf.okta.client.api.LogEvents;
import gov.texas.esb.cxf.okta.client.service.OktaService;
import gov.texas.okta.client.util.TestClient;



/**
 * Okta API
 *
 * <p>Allows customers to easily access the Okta API
 *
 * API tests for LogApi 
 */
public class LogApiTest {


	OktaService client;
	
	@Before
	public void init() {
		
		client=TestClient.createTestClient();
	}

 
    //TODO write a test polling over a loop and verify the since/to times work correctly when range is of dates is too big
    //for the alloted number returns.
    
    /**
     * Fetch a list of events from your Okta organization system log.
     *
     * The Okta System Log API provides read access to your organization’s system log. This API provides more functionality than the Events API
     * @throws JsonProcessingException 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRangeOfLogsTest() throws JsonProcessingException {
	
      
        LocalDateTime until = Year.of(2019).atMonth(12).atDay(15).atTime(1,1);
        LocalDateTime since = Year.of(2019).atMonth(11).atDay(1).atTime(1,1);
        
        LogEvents response = client.getLogEvents(since,until);
       
        
        ObjectMapper mapper = new ObjectMapper();
        
        System.out.println(mapper.writerWithDefaultPrettyPrinter().writeValueAsString(response));

   
    }
}
